---
title: "Police Complaints"
author: "Fahim Ahmed"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```

```{r, include=FALSE}
raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>%
  select(officer_id, po_race, po_sex)
```

```{r, clean_data, include=FALSE}
#outputs the officers with the most complaints in descending order.
clean_data <- raw_data %>%
  group_by(officer_id) %>%
  summarize(total = n()) %>% #n() is basically count
  mutate(compl_dec = ntile(total, 10)) %>%
  group_by(compl_dec) %>%
  summarize(compl_total = sum(total)) %>%
  mutate(compl_percentage = compl_total / sum(compl_total))

```

```{r, plot_data, echo=FALSE}
clean_data %>%
  ggplot(mapping = aes(x = compl_dec, y = compl_percentage)) +
  geom_col(fill = "#add8e6", color = "black") +
  scale_x_continuous(breaks = c(1:10)) +
  scale_y_continuous(labels = scales::percent_format()) + 
  theme_classic() +
  labs(title = "Distribution of Police Complaints in Philadelphia by Decile",
       subtitle = "The police officers with the most complaints have a\ndisproportionately larger percentage of the total complaints.",
       x = "Officer Decile",
       y = "Percentage of Complaints",
       caption = "Source: Financial Times")
```